### ISSUE TITLE
Error from dgl 

### ISSUE THREAD

**Issue by ericzzj1989** [robocomp/sngnn#10]
When running example.py, there exists an error "ModuleNotFoundError: No module named 'dgl.batched_graph'". Is somebody willing to help me solve this problem? Many thanks.

**Comment by ljmanso** [comment]
Hello @ericzzj1989,

You need to install dgl. Please, follow the instructions you will find at https://www.dgl.ai/pages/start.html

Let us know if you have any problem with that.

Luis

**Comment by ericzzj1989** [comment]
> Hello @ericzzj1989,
> 
> You need to install dgl. Please, follow the instructions you will find at https://www.dgl.ai/pages/start.html
> 
> Let us know if you have any problem with that.
> 
> Luis

@ljmanso Many thanks for your kind reply.
Yes, I actually do install dgl (with command "conda install -c dglteam dgl-cuda10.1"). But there is still the error "ModuleNotFoundError: No module named 'dgl.batched_graph'" when running example.py.

**Comment by ericzzj1989** [comment]
@ljmanso The console information for your reference. Many thanks.

Traceback (most recent call last):
  File "example.py", line 8, in <module>
    sngnn = SNGNN()
  File "/home/eric/eric_doc/KSU intern/code/sngnn/sndgAPI.py", line 43, in __init__
    self.params = pickle.load(open('SNGNN_PARAMETERS.prms', 'rb'), fix_imports=True)
ModuleNotFoundError: No module named 'dgl.batched_graph'

**Comment by ljmanso** [comment]
What's the DGL version you have installed? I just checked and it seems it stopped working after the latest update 0.4.3. Could you please try downgrading to 0.4.2 while we update the code?

**Comment by ericzzj1989** [comment]
@ljmanso Many thanks for your kind reply.
One point I want to specify is that the system I am now using is Ubuntu 18.04. Is it suitable for your code?

**Comment by ericzzj1989** [comment]
@ljmanso I upgraded DGL version to 0.4.2 and it worked finally. Thanks a lot for your solution and patience!

**Comment by ericzzj1989** [comment]
@ljmanso  I downgraded DGL version to 0.4.2 and it worked finally. Thanks a lot for your solution and patience!
