### ISSUE TITLE
No module named 'IceStorm'

### ISSUE THREAD

**Issue by bianyangT** [robocomp/sngnn#14]
Hello! I'm very interested in the application of robot path planning in social environments recently, and I hope to use your "SONATA" to generate some data. 
However, I encountered an issue when running 'bash run.sh', which indicates a problem occurring in SONATA/controller/src/controller.py. 
The specific error message is as follows:
"No module named 'IceStorm'."
Looking forward to your response!

**Comment by ljmanso** [comment]
Hi @bianyangT,

Sory for the delay, I just saw the issue. That means that you need to install the package `zeroc-ice`.

I hope that helps,
Luis
