### ISSUE TITLE
helps for new contributors?

### ISSUE THREAD

**Issue by amitYadavDev** [robocomp/sngnn#3]

**Comment by ljmanso** [comment]
Hello @amit6663.

I am not sure if you are asking for how to contribute or for guidance to understand the project.

The software of the project has currently two main components. The ML subsystem is used to train and provide an API for the graph neural network model. The other component is a script used to randomly generate scenarios, which was used to generate the dataset that the ML subsystem used. If your doubts are regarding the code, it would be great if you could ask a more specific question. If they are related to the GNN model used, it is explained in https://arxiv.org/abs/1909.09003.

If what you want to know is how can you help, there are plenty of options. We are going to add new issues for all the improvements that we have considered.

Thank you for your interest in the project.

Luis
