### ISSUE TITLE
Error when training the sngnn model.

### ISSUE THREAD

**Issue by Devansh-S** [robocomp/sngnn#8]
Hello,
I cannot train the sngnn model as the dataset for training the model is missing.

Traceback (most recent call last):
  File "train.py", line 521, in <module>
    fw='pg')
  File "train.py", line 287, in main
    train_dataset = SocNavDataset(training_file, mode='train', alt=graph_type)
  File "/Users/rehan/sngnn/socnav.py", line 650, in __init__
    self._load(alt)
  File "/Users/rehan/sngnn/socnav.py", line 658, in _load
    for line in open(self.path).readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'socnav_training_small.json'

**Comment by Ronit-j** [comment]
Hello @Devansh-S,
The dataset files are available here ([https://github.com/ljmanso/SocNav1](https://github.com/ljmanso/SocNav1)). Please place the required files in the directory and you'll be able to train now. Thanks for letting us know. I have updated the Readme to include this information.
Regards,
Ronit
