### ISSUE TITLE
How to run this code to generate the video result？

### ISSUE THREAD

**Issue by ericzzj1989** [robocomp/sngnn#9]
Hello, would you mind writing a Redme file to demonstrate how to run this code to obtain the video results?

**Comment by ljmanso** [comment]
Hello @ericzzj1989,

I have added some information in the `README.md` file. You will need to pull the last version of the repository, as there was a minor bug that prevented the script to evaluate random scenes.

Simply use the command line to get to the repository source code, then get into the `scenario_editor directory` and run the `sndg.py` script. It is the script that was used to generate the dataset used, but it can also be used to generate random scenes and test the results:

```
cd scenario_editor
python3 sndg.py
```

Once the interface shows up, you just need to check the automatically estimate checkbox. Every time you click on get new sample a new scene will appear and will be assessed automatically.
